# plan.yml
name: Terraform Plan
description: 'Terraform plan description'
inputs:
  environment:
    description: 'Environment to deploy to'
    required: true
runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - id: gcp-sdk
    name: Set up Cloud SDK
    uses: google-github-actions/setup-gcloud@v0
    with:
      install_components: alpha

  - id: tf-config
    # copy provider and tfvars files
    name: Copy Terraform output files
    shell: bash
    run: |
      gcloud alpha storage cp -r \
        "gs://$${{env.FAST_OUTPUTS_BUCKET}}/providers/$${{env.TF_PROVIDERS_FILE}}" ./
      gcloud alpha storage cp -r \
        "gs://$${{env.FAST_OUTPUTS_BUCKET}}/tfvars" ./
      for f in $${{env.TF_VAR_FILES}}; do
        ln -s "tfvars/$f" ./
      done

  - id: tf-setup
    name: Set up Terraform
    uses: hashicorp/setup-terraform@v2.0.3
    with:
      terraform_version: $${{ env.TF_VERSION }}

  # run Terraform init/validate/plan
  - id: tf-init
    name: Terraform init
    shell: bash
    run: |
      terraform init -no-color

  - id: tf-validate
    name: Terraform Validate
    shell: bash
    run: terraform validate -no-color

  - name: Terraform Plan
    shell: bash
    run: terraform plan -input=false -var-file=${{ inputs.environment }} -out=tfplan

  - name: Save Plan
    uses: actions/upload-artifact@v2
    with:
      name: tfplan
      path: ./tfplan

