# workflow.yml
name: Terraform Plan and Apply
on:
  push:
    branches:
      - main
jobs:
  plan:
    name: Terraform Plan
    uses: owner/plan@v1
  apply:
    name: Terraform Apply
    uses: owner/apply@v1
