# apply.yml
name: Terraform Apply
description: 'Terraform apply description'
runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - id: tf-init
    name: Terraform init
    shell: bash
    run: |
      terraform init -no-color

  - name: Download Plan
    uses: actions/download-artifact@v2
    with:
      name: tfplan

  - id: tf-apply
    name: Terraform apply
    shell: bash
    run: |
      terraform apply -input=false -auto-approve -no-color ../plan.out
